name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'  # або інша версія Node.js

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm run test -- --watch=false --browsers=ChromeHeadless

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar-host-url: https://sonarcloud.io
          sonar-login: ${{ secrets.SONAR_TOKEN }}
